import { Sound } from '../app/sound.model';

export const SOUNDS: Sound[] = [
  {
    id: 11,
    track: '/assets/sounds/wind.mp3',
    img: 'assets/images/wind.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Wind',
  },
  {
    id: 12,
    track: '/assets/sounds/clouds.wav',
    img: 'assets/images/source_icons_cloud.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Cloudy',
  },
  {
    id: 13,
    track: '/assets/sounds/airplane.mp3',
    img: 'assets/images/source_icons_airplane-helix-45deg.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Airplane',
  },
  {
    id: 14,
    track: '/assets/sounds/campfire.mp3',
    img: 'assets/images/source_icons_bonfire.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Bonfire',
  },
  {
    id: 15,
    track: '/assets/sounds/birds.mp3',
    img: 'assets/images/bird.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Birds',
  },
  {
    id: 16,
    track: '/assets/sounds/bubbles.mp3',
    img: 'assets/images/bubbles.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Bubbles',
  },
  {
    id: 17,
    track: '/assets/sounds/rain-on-tent.mp3',
    img: 'assets/images/rain-tent.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Rain on Tent',
  },
  {
    id: 18,
    track: '/assets/sounds/bus.mp3',
    img: 'assets/images/bus.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Bus Inside',
  },
  {
    id: 19,
    track: '/assets/sounds/restaurnt.mp3',
    img: 'assets/images/restaurnt.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Restaurnt',
  },
  {
    id: 20,
    track: '/assets/sounds/train-station.mp3',
    img: 'assets/images/train-station.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Train Station',
  },
  {
    id: 21,
    track: '/assets/sounds/super-market.mp3',
    img: 'assets/images/super-market.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Super Market',
  },
  {
    id: 22,
    track: '/assets/sounds/street.mp3',
    img: 'assets/images/street.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Street',
  },
  {
    id: 23,
    track: '/assets/sounds/forest.mp3',
    img: 'assets/images/forest.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Forest',
  },
  {
    id: 24,
    track: '/assets/sounds/train.mp3',
    img: 'assets/images/train.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'train',
  },
  {
    id: 25,
    track: '/assets/sounds/summer-night.mp3',
    img: 'assets/images/summer-night.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Summer Night',
  },
  {
    id: 26,
    track: '/assets/sounds/coffee-shop.mp3',
    img: 'assets/images/coffee-shop.svg',
    volume: 3,
    playing: false,
    type: 0,
    name: 'Coffee Shop',
  },
];
